#!/bin/sh
# -------
# File:        virt-upstart-create
# Description: Create an upstart job for a given virtual machine
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

VM_PREFIX="virt-"

. /usr/share/virt-upstart-manager/upstart-common

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") VM_NAME [VM_DEPENDS_LIST ...]"
}

[ "$1" ] || usage

VIRT_MACHINE=""
OR_STOPPING_RELATED_JOBS=""
AND_STARTED_RELATED_JOBS=""
DEFAULT_FILE="/etc/default/virt-upstart"
if [ -r "$DEFAULT_FILE" ] ; then
	. "$DEFAULT_FILE"
	for j in $STARTED_RELATED_JOBS ; do
		AND_STARTED_RELATED_JOBS="and started $j\n"
	done
	for j in $STOPPING_RELATED_JOBS ; do
		OR_STOPPING_RELATED_JOBS="or stopping $j\n"
	done
fi

while [ "$1" ]; do
	vm_test "$1" || die "Error: \"$1\" is not a valid virtual machine name"
	UPSTART_JOB="${VM_PREFIX}${1}"
	if [ -z "$VIRT_MACHINE" ] ; then
		VIRT_MACHINE="$1"
		VIRT_JOB="$UPSTART_JOB"
	else
		[ -r "/etc/init/${UPSTART_JOB}.conf" ] || die "Error: There is not an upstart job named \"$UPSTART_JOB\""
		AND_STARTED_RELATED_JOBS="$AND_STARTED_RELATED_JOBS and started $UPSTART_JOB\n        "
#		OR_STOPPING_RELATED_JOBS="$OR_STOPPING_RELATED_JOBS or stopping $UPSTART_JOB\n        "
	fi
	shift
done
TARGET_FILE="/etc/init/${VIRT_JOB}.conf"
INITD_FILE="/etc/init.d/${VIRT_JOB}"
[ ! -r "$TARGET_FILE" ] || die "Error: \"$TARGET_FILE\" already exists. Exiting"

sed -e "s%_@_AND_STARTED_RELATED_JOBS_@_%$AND_STARTED_RELATED_JOBS%g;s%_@_OR_STOPPING_RELATED_JOBS_@_%$OR_STOPPING_RELATED_JOBS%g;s%_@_VIRT_MACHINE_@_%$VIRT_MACHINE%g;s%_@_VIRT_JOB_@_%$VIRT_JOB%g" /usr/share/virt-upstart-manager/virt-job-conf.template > $TARGET_FILE || die "Error generating \"$TARGET_FILE\""
if [ "$TARGET_FILE" ] ; then
	rm -f "$INITD_FILE"
	ln -s /lib/init/upstart-job "$INITD_FILE"
fi

echo "\"$TARGET_FILE\" successfully generated"
exit 0

